version: "3"
services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=testing
      - RABBITMQ_DEFAULT_PASS=123456

  api_gateway:
    build:
      context: ./api_gateway
    ports:
      - "5001:5001"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=queue_cursos
      - RABBITMQ_USER=testing
      - RABBITMQ_PASS=123456
    depends_on:
      - rabbitmq

  cursos_1:
    build:
      context: ./cursos
    ports:
      - "5002:5002"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=queue_cursos
      - PORT=5002
      - RABBITMQ_USER=testing
      - RABBITMQ_PASS=123456
      - MONITOR_URL=http://monitor:5003
    mem_limit: 128m

  cursos_2:
    build:
      context: ./cursos
    ports:
      - "5012:5012"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=queue_cursos
      - PORT=5012
      - RABBITMQ_USER=testing
      - RABBITMQ_PASS=123456
      - MONITOR_URL=http://monitor:5003
    mem_limit: 128m

  cursos_3:
    build:
      context: ./cursos
    ports:
      - "5022:5022"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=queue_cursos
      - PORT=5022
      - RABBITMQ_USER=testing
      - RABBITMQ_PASS=123456
      - MONITOR_URL=http://monitor:5003
    mem_limit: 128m

  monitor:
    build:
      context: ./monitor
    ports:
      - "5003:5003"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  auth:
    build:
      context: ./auth
    ports:
      - "5004:5004"
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:///Database.db
      - SECRET_KEY=secretkey
      - PORT=5004
    mem_limit: 128m
